<?php

use Illuminate\Database\Seeder;

class BookingSubTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    
        DB::table('booking_tax_sub_types')->insert([

            //week days=> 0
            
             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>1,'is_weekend'=>0,'ammount'=>20000.0,'floor'=>false],
             ['sub_type_description'=>'for an Additional one hour','parent_id'=>1,'is_weekend'=>0,'ammount'=>2500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposits','parent_id'=>1,'is_weekend'=>0,'ammount'=>15000.0,'floor'=>false],
             ['sub_type_description'=>'For Water','parent_id'=>1,'is_weekend'=>0,'ammount'=>1500.0,'floor'=>false],
             ['sub_type_description'=>'for a single show not exceeding 03 hours','parent_id'=>2,'is_weekend'=>0,'ammount'=>10000.0,'floor'=>false],
             ['sub_type_description'=>'for 02  shows not exceeding 03 hours','parent_id'=>2,'is_weekend'=>0,'ammount'=>14000.0,'floor'=>false],
             ['sub_type_description'=>'for 03   shows  not exceeding 03 hours','parent_id'=>2,'is_weekend'=>0,'ammount'=>15000.0,'floor'=>false],
             ['sub_type_description'=>'for supply of water','parent_id'=>2,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
             ['sub_type_description'=>'For a single show not exceeding 03 hours','parent_id'=>3,'is_weekend'=>0,'ammount'=>7000.0,'floor'=>false],
             ['sub_type_description'=>'For 02 shows not exceeding 03 hours','parent_id'=>3,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For 03 shows not exceeding 03 hours','parent_id'=>3,'is_weekend'=>0,'ammount'=>9000.0,'floor'=>false],
             ['sub_type_description'=>'For every one hour exceeding','parent_id'=>3,'is_weekend'=>0,'ammount'=>1500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>3,'is_weekend'=>0,'ammount'=>10000.0,'floor'=>false],
             ['sub_type_description'=>'For supply of water','parent_id'=>3,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'For a single day (for 06 hours)','parent_id'=>4,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
             ['sub_type_description'=>'For every additional one hour','parent_id'=>4,'is_weekend'=>0,'ammount'=>1500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>4,'is_weekend'=>0,'ammount'=>10000.0,'floor'=>false],
             ['sub_type_description'=>'For Water','parent_id'=>4,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'For a period  not exceeding 06 hours','parent_id'=>5,'is_weekend'=>0,'ammount'=>7000.0,'floor'=>false],
             ['sub_type_description'=>'Additional one hour','parent_id'=>5,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>5,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>5,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>6,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>6,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>6,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>6,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>7,'is_weekend'=>0,'ammount'=>7000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>7,'is_weekend'=>0,'ammount'=>750.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>7,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>7,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>8,'is_weekend'=>0,'ammount'=>8500.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>8,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>8,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>8,'is_weekend'=>0,'ammount'=>1500.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>9,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>9,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>9,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>9,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>10,'is_weekend'=>0,'ammount'=>6000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>10,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>10,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>10,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>11,'is_weekend'=>0,'ammount'=>4500.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>11,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>11,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>11,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>12,'is_weekend'=>0,'ammount'=>7000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>12,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>12,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>12,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>13,'is_weekend'=>0,'ammount'=>6000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>13,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>13,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>13,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>14,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>14,'is_weekend'=>0,'ammount'=>1500.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>14,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>14,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>15,'is_weekend'=>0,'ammount'=>6000.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>15,'is_weekend'=>0,'ammount'=>750.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>15,'is_weekend'=>0,'ammount'=>5000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>15,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>16,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>16,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>16,'is_weekend'=>0,'ammount'=>8000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>16,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>17,'is_weekend'=>0,'ammount'=>6500.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>17,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>17,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>17,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>18,'is_weekend'=>0,'ammount'=>8500.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>18,'is_weekend'=>0,'ammount'=>1000.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>18,'is_weekend'=>0,'ammount'=>10000.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>18,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>19,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>19,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>19,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
             ['sub_type_description'=>'For water','parent_id'=>19,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
     
             //town hall no 2 

             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>20,'is_weekend'=>1,'ammount'=>6500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>20,'is_weekend'=>1,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>20,'is_weekend'=>1,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>20,'is_weekend'=>1,'ammount'=>750.0,'floor'=>false],
            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>21,'is_weekend'=>1,'ammount'=>3500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>21,'is_weekend'=>1,'ammount'=>375.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>21,'is_weekend'=>1,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>21,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>22,'is_weekend'=>1,'ammount'=>5500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>22,'is_weekend'=>1,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>22,'is_weekend'=>1,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>22,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>23,'is_weekend'=>1,'ammount'=>5500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>23,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>23,'is_weekend'=>1,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>23,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>24,'is_weekend'=>1,'ammount'=>4000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>24,'is_weekend'=>1,'ammount'=>300.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>24,'is_weekend'=>1,'ammount'=>2500.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>24,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>25,'is_weekend'=>1,'ammount'=>3500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>25,'is_weekend'=>1,'ammount'=>375.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>25,'is_weekend'=>1,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>26,'is_weekend'=>1,'ammount'=>4000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>26,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>26,'is_weekend'=>1,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>26,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>27,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>27,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>27,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>27,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],

            

            //stadium
            // week days -> 0 lower floor -> 0
           
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>28,'is_weekend'=>0,'floor'=>0,'ammount'=>17000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>28,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>28,'is_weekend'=>0,'floor'=>0,'ammount'=>10000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>29,'is_weekend'=>0,'floor'=>0,'ammount'=>12500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>29,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>29,'is_weekend'=>0,'floor'=>0,'ammount'=>10000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>30,'is_weekend'=>0,'floor'=>0,'ammount'=>11000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>30,'is_weekend'=>0,'floor'=>0,'ammount'=>750.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>30,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>31,'is_weekend'=>0,'floor'=>0,'ammount'=>11000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>31,'is_weekend'=>0,'floor'=>0,'ammount'=>750.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>31,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>32,'is_weekend'=>0,'floor'=>0,'ammount'=>12000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>32,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>32,'is_weekend'=>0,'floor'=>0,'ammount'=>10000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>33,'is_weekend'=>0,'floor'=>0,'ammount'=>6500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>33,'is_weekend'=>0,'floor'=>0,'ammount'=>750.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>33,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>34,'is_weekend'=>0,'floor'=>0,'ammount'=>5500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>34,'is_weekend'=>0,'floor'=>0,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>34,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>35,'is_weekend'=>0,'floor'=>0,'ammount'=>8000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>35,'is_weekend'=>0,'floor'=>0,'ammount'=>750.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>35,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>36,'is_weekend'=>0,'floor'=>0,'ammount'=>5500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>36,'is_weekend'=>0,'floor'=>0,'ammount'=>750.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>36,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>37,'is_weekend'=>0,'floor'=>0,'ammount'=>10000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>37,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>37,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>38,'is_weekend'=>0,'floor'=>0,'ammount'=>5000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>38,'is_weekend'=>0,'floor'=>0,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>38,'is_weekend'=>0,'floor'=>0,'ammount'=>5000.0],
             ['sub_type_description'=>'From 6.00pm to 6.00am ','parent_id'=>39,'is_weekend'=>0,'floor'=>0,'ammount'=>2500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>39,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>39,'is_weekend'=>0,'floor'=>0,'ammount'=>2000.0],
             ['sub_type_description'=>'For a day (06hrs)','parent_id'=>40,'is_weekend'=>0,'floor'=>0,'ammount'=>20000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>40,'is_weekend'=>0,'floor'=>0,'ammount'=>12000.0],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>41,'is_weekend'=>0,'floor'=>0,'ammount'=>7000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>41,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>41,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'For watching sports games','parent_id'=>42,'is_weekend'=>0,'floor'=>0,'ammount'=>10000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>42,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>42,'is_weekend'=>0,'floor'=>0,'ammount'=>7500.0],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>43,'is_weekend'=>0,'floor'=>0,'ammount'=>8000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>43,'is_weekend'=>0,'floor'=>0,'ammount'=>1000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>43,'is_weekend'=>0,'floor'=>0,'ammount'=>10000.0],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>44,'is_weekend'=>0,'floor'=>0,'ammount'=>0.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>44,'is_weekend'=>0,'floor'=>0,'ammount'=>0.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>44,'is_weekend'=>0,'floor'=>0,'ammount'=>0.0],

             //week day -> 0 upper floor -> 1

             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>28,'is_weekend'=>0,'floor'=>1,'ammount'=>8000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>28,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>28,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>29,'is_weekend'=>0,'floor'=>1,'ammount'=>7000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>29,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>29,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>30,'is_weekend'=>0,'floor'=>1,'ammount'=>6000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>30,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>30,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>31,'is_weekend'=>0,'floor'=>1,'ammount'=>6000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>31,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>31,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>32,'is_weekend'=>0,'floor'=>1,'ammount'=>6000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>32,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>32,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>33,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>33,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>33,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>34,'is_weekend'=>0,'floor'=>1,'ammount'=>3500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>34,'is_weekend'=>0,'floor'=>1,'ammount'=>300.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>34,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>35,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>35,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>35,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>36,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>36,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>36,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>37,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>37,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>37,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>38,'is_weekend'=>0,'floor'=>1,'ammount'=>3000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>38,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>38,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'From 6.00pm to 6.00am ','parent_id'=>39,'is_weekend'=>0,'floor'=>1,'ammount'=>1500.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>39,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>39,'is_weekend'=>0,'floor'=>1,'ammount'=>1500.0],
             ['sub_type_description'=>'For a day (06hrs)','parent_id'=>40,'is_weekend'=>0,'floor'=>1,'ammount'=>20000.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>40,'is_weekend'=>0,'floor'=>1,'ammount'=>12000.0],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>41,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>41,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>41,'is_weekend'=>0,'floor'=>1,'ammount'=>4000.0],
             ['sub_type_description'=>'For watching sports games','parent_id'=>42,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>42,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>42,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>43,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>43,'is_weekend'=>0,'floor'=>1,'ammount'=>500.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>43,'is_weekend'=>0,'floor'=>1,'ammount'=>5000.0],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>44,'is_weekend'=>0,'floor'=>1,'ammount'=>0.0],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>44,'is_weekend'=>0,'floor'=>1,'ammount'=>0.0],
             ['sub_type_description'=>'Security Deposit','parent_id'=>44,'is_weekend'=>0,'floor'=>1,'ammount'=>0.0],

             //samanala ground
             ['sub_type_description'=>'for a single day','parent_id'=>45,'ammount'=>5000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'payment of fees per day','parent_id'=>46,'ammount'=>20000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'Security Deposit(Agreement has to be signed)','parent_id'=>46,'ammount'=>10000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>47,'ammount'=>8000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'Security Deposit','parent_id'=>47,'ammount'=>10000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>48,'ammount'=>1000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>49,'ammount'=>2500.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>50,'ammount'=>2000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>51,'ammount'=>4000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>52,'ammount'=>16000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'Security Deposit  (Agreement has  to be signed)','parent_id'=>52,'ammount'=>15000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'For rehearsal per day Rs 5000/=','parent_id'=>52,'ammount'=>5000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'To clean per day','parent_id'=>52,'ammount'=>5000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'payment','parent_id'=>53,'ammount'=>2500.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>54,'ammount'=>10000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'Security  Deposit','parent_id'=>54,'ammount'=>7500.0,'floor'=>false,'is_weekend'=>false], 
             ['sub_type_description'=>'License Fee for a day(persons who aren’t in town area)','parent_id'=>54,'ammount'=>1000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>55,'ammount'=>4000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'Security  Deposit','parent_id'=>55,'ammount'=>7500.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per hour','parent_id'=>56,'ammount'=>8000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'For every additional hour or part of it','parent_id'=>56,'ammount'=>2000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>57,'ammount'=>5000.0,'floor'=>false,'is_weekend'=>false],           
             ['sub_type_description'=>'Security  Deposit','parent_id'=>57,'ammount'=>7500.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a per day','parent_id'=>58,'ammount'=>2500.0,'floor'=>false,'is_weekend'=>false],


              //Hiyare tank
             ['sub_type_description'=>'for a day','parent_id'=>60,'ammount'=>8000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for other charge','parent_id'=>61,'ammount'=>0.0,'floor'=>false,'is_weekend'=>false],

             //dharmapala graden
             ['sub_type_description'=>'for a day','parent_id'=>62,'ammount'=>17000.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for any additional sqrt','parent_id'=>63,'ammount'=>0.0,'floor'=>false,'is_weekend'=>false],
             ['sub_type_description'=>'for a day','parent_id'=>64,'ammount'=>40000.0,'floor'=>false,'is_weekend'=>false],

             
             ['sub_type_description'=>'for a one night','parent_id'=>66,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],

             ['sub_type_description'=>'for a day','parent_id'=>67,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
             ['sub_type_description'=>'for a day','parent_id'=>68,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
             ['sub_type_description'=>'additional charge','parent_id'=>69,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],


             

             
             
         ]);

         DB::table('booking_tax_sub_types')->insert([

            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>1,'is_weekend'=>1,'ammount'=>22500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>1,'is_weekend'=>1,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>1,'is_weekend'=>1,'ammount'=>15000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>1,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'for a single show not exceeding 03 hours','parent_id'=>2,'is_weekend'=>1,'ammount'=>12000.0,'floor'=>false],
            ['sub_type_description'=>'for 02  shows not exceeding 03 hours','parent_id'=>2,'is_weekend'=>1,'ammount'=>16000.0,'floor'=>false],
            ['sub_type_description'=>'for 03   shows  not exceeding 03 hours','parent_id'=>2,'is_weekend'=>1,'ammount'=>18000.0,'floor'=>false],
            ['sub_type_description'=>'for supply of water','parent_id'=>2,'is_weekend'=>1,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'For a single show not exceeding 03 hours','parent_id'=>3,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For 02 shows not exceeding 03 hours','parent_id'=>3,'is_weekend'=>1,'ammount'=>9000.0,'floor'=>false],
            ['sub_type_description'=>'For 03 shows not exceeding 03 hours','parent_id'=>3,'is_weekend'=>1,'ammount'=>10000.0,'floor'=>false],
            ['sub_type_description'=>'For every one hour exceeding','parent_id'=>3,'is_weekend'=>1,'ammount'=>2000.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>3,'is_weekend'=>1,'ammount'=>10000.0,'floor'=>false],
            ['sub_type_description'=>'For supply of water','parent_id'=>3,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'For a single day (for 06 hours)','parent_id'=>4,'is_weekend'=>1,'ammount'=>8500.0,'floor'=>false],
            ['sub_type_description'=>'For every additional one hour','parent_id'=>4,'is_weekend'=>1,'ammount'=>2000.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>4,'is_weekend'=>1,'ammount'=>10000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>4,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'For a period  not exceeding 06 hours','parent_id'=>5,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'Additional one hour','parent_id'=>5,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>5,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>5,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>6,'is_weekend'=>1,'ammount'=>8500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>6,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>6,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>6,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>7,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>7,'is_weekend'=>1,'ammount'=>1250.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>7,'is_weekend'=>1,'ammount'=>7500.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>7,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>8,'is_weekend'=>1,'ammount'=>9500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>8,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>8,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>8,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>9,'is_weekend'=>1,'ammount'=>9000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>9,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>9,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>9,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>10,'is_weekend'=>1,'ammount'=>7500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>10,'is_weekend'=>1,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>10,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>10,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>11,'is_weekend'=>1,'ammount'=>5500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>11,'is_weekend'=>1,'ammount'=>1000.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>11,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>11,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>12,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>12,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>12,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>12,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>13,'is_weekend'=>1,'ammount'=>7000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>13,'is_weekend'=>1,'ammount'=>750.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>13,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>13,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>14,'is_weekend'=>1,'ammount'=>10000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>14,'is_weekend'=>1,'ammount'=>2500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>14,'is_weekend'=>1,'ammount'=>7500.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>14,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>15,'is_weekend'=>1,'ammount'=>7000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>15,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>15,'is_weekend'=>1,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>15,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>16,'is_weekend'=>1,'ammount'=>9000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>16,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>16,'is_weekend'=>1,'ammount'=>8000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>16,'is_weekend'=>1,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>17,'is_weekend'=>1,'ammount'=>7500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>17,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>17,'is_weekend'=>1,'ammount'=>7500.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>17,'is_weekend'=>1,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>18,'is_weekend'=>1,'ammount'=>10000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>18,'is_weekend'=>1,'ammount'=>1500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>18,'is_weekend'=>1,'ammount'=>10000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>18,'is_weekend'=>1,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>19,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>19,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>19,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>19,'is_weekend'=>1,'ammount'=>0.0,'floor'=>false],
       
            //town hall no 2 

            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>20,'is_weekend'=>0,'ammount'=>7500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>20,'is_weekend'=>0,'ammount'=>750.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>20,'is_weekend'=>0,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>20,'is_weekend'=>0,'ammount'=>750.0,'floor'=>false],
            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>21,'is_weekend'=>0,'ammount'=>4000.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>21,'is_weekend'=>0,'ammount'=>450.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>21,'is_weekend'=>0,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>21,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>22,'is_weekend'=>0,'ammount'=>6500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>22,'is_weekend'=>0,'ammount'=>750.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>22,'is_weekend'=>0,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>22,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>23,'is_weekend'=>0,'ammount'=>6500.0,'floor'=>false],
            ['sub_type_description'=>'for an Additional one hour','parent_id'=>23,'is_weekend'=>0,'ammount'=>500.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposits','parent_id'=>23,'is_weekend'=>0,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'For Water','parent_id'=>23,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>24,'is_weekend'=>0,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>24,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>24,'is_weekend'=>0,'ammount'=>2500.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>24,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>25,'is_weekend'=>0,'ammount'=>4500.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>25,'is_weekend'=>0,'ammount'=>450.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>25,'is_weekend'=>0,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>26,'is_weekend'=>0,'ammount'=>5000.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>26,'is_weekend'=>0,'ammount'=>450.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>26,'is_weekend'=>0,'ammount'=>3000.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>26,'is_weekend'=>0,'ammount'=>400.0,'floor'=>false],
            ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>27,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'for every Additional one hour','parent_id'=>27,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'Security Deposit','parent_id'=>27,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],
            ['sub_type_description'=>'For water','parent_id'=>27,'is_weekend'=>0,'ammount'=>0.0,'floor'=>false],

           //stadium
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>28,'is_weekend'=>1,'floor'=>0,'ammount'=>22000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>28,'is_weekend'=>1,'floor'=>0,'ammount'=>1500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>28,'is_weekend'=>1,'floor'=>0,'ammount'=>10000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>29,'is_weekend'=>1,'floor'=>0,'ammount'=>15500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>29,'is_weekend'=>1,'floor'=>0,'ammount'=>1500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>29,'is_weekend'=>1,'floor'=>0,'ammount'=>10000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>30,'is_weekend'=>1,'floor'=>0,'ammount'=>13000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>30,'is_weekend'=>1,'floor'=>0,'ammount'=>1000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>30,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>31,'is_weekend'=>1,'floor'=>0,'ammount'=>13000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>31,'is_weekend'=>1,'floor'=>0,'ammount'=>1000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>31,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>32,'is_weekend'=>1,'floor'=>0,'ammount'=>15000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>32,'is_weekend'=>1,'floor'=>0,'ammount'=>1500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>32,'is_weekend'=>1,'floor'=>0,'ammount'=>10000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>33,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>33,'is_weekend'=>1,'floor'=>0,'ammount'=>1000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>33,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>34,'is_weekend'=>1,'floor'=>0,'ammount'=>6000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>34,'is_weekend'=>1,'floor'=>0,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>34,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>35,'is_weekend'=>1,'floor'=>0,'ammount'=>8000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>35,'is_weekend'=>1,'floor'=>0,'ammount'=>1000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>35,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>36,'is_weekend'=>1,'floor'=>0,'ammount'=>6500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>36,'is_weekend'=>1,'floor'=>0,'ammount'=>1000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>36,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>37,'is_weekend'=>1,'floor'=>0,'ammount'=>12000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>37,'is_weekend'=>1,'floor'=>0,'ammount'=>1250.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>37,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>38,'is_weekend'=>1,'floor'=>0,'ammount'=>6000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>38,'is_weekend'=>1,'floor'=>0,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>38,'is_weekend'=>1,'floor'=>0,'ammount'=>5000.0],
            ['sub_type_description'=>'From 6.00pm to 6.00am ','parent_id'=>39,'is_weekend'=>1,'floor'=>0,'ammount'=>2500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>39,'is_weekend'=>1,'floor'=>0,'ammount'=>1000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>39,'is_weekend'=>1,'floor'=>0,'ammount'=>2000.0],
            ['sub_type_description'=>'For a day (06hrs)','parent_id'=>40,'is_weekend'=>1,'floor'=>0,'ammount'=>20000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>40,'is_weekend'=>1,'floor'=>0,'ammount'=>12000.0],
            ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>41,'is_weekend'=>1,'floor'=>0,'ammount'=>8000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>41,'is_weekend'=>1,'floor'=>0,'ammount'=>1250.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>41,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'For watching sports games','parent_id'=>42,'is_weekend'=>1,'floor'=>0,'ammount'=>12000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>42,'is_weekend'=>1,'floor'=>0,'ammount'=>1250.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>42,'is_weekend'=>1,'floor'=>0,'ammount'=>7500.0],
            ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>43,'is_weekend'=>1,'floor'=>0,'ammount'=>10000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>43,'is_weekend'=>1,'floor'=>0,'ammount'=>1500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>43,'is_weekend'=>1,'floor'=>0,'ammount'=>10000.0],
            ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>44,'is_weekend'=>1,'floor'=>0,'ammount'=>0.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>44,'is_weekend'=>1,'floor'=>0,'ammount'=>0.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>44,'is_weekend'=>1,'floor'=>0,'ammount'=>0.0],




            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>28,'is_weekend'=>1,'floor'=>1,'ammount'=>9000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>28,'is_weekend'=>1,'floor'=>1,'ammount'=>750.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>28,'is_weekend'=>1,'floor'=>1,'ammount'=>5000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>29,'is_weekend'=>1,'floor'=>1,'ammount'=>8000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>29,'is_weekend'=>1,'floor'=>1,'ammount'=>750.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>29,'is_weekend'=>1,'floor'=>1,'ammount'=>5000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>30,'is_weekend'=>1,'floor'=>1,'ammount'=>7000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>30,'is_weekend'=>1,'floor'=>1,'ammount'=>750.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>30,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>31,'is_weekend'=>1,'floor'=>1,'ammount'=>7000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>31,'is_weekend'=>1,'floor'=>1,'ammount'=>750.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>31,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>32,'is_weekend'=>1,'floor'=>1,'ammount'=>7000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>32,'is_weekend'=>1,'floor'=>1,'ammount'=>750.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>32,'is_weekend'=>1,'floor'=>1,'ammount'=>5000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>33,'is_weekend'=>1,'floor'=>1,'ammount'=>6000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>33,'is_weekend'=>1,'floor'=>1,'ammount'=>750.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>33,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>34,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>34,'is_weekend'=>1,'floor'=>1,'ammount'=>400.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>34,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>35,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>35,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>35,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>36,'is_weekend'=>1,'floor'=>1,'ammount'=>4500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>36,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>36,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>37,'is_weekend'=>1,'floor'=>1,'ammount'=>6000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>37,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>37,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>38,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>38,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>38,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'From 6.00pm to 6.00am ','parent_id'=>39,'is_weekend'=>1,'floor'=>1,'ammount'=>1500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>39,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>39,'is_weekend'=>1,'floor'=>1,'ammount'=>1500.0],
            ['sub_type_description'=>'For a day (06hrs)','parent_id'=>40,'is_weekend'=>1,'floor'=>1,'ammount'=>20000.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>40,'is_weekend'=>1,'floor'=>1,'ammount'=>12000.0],
            ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>41,'is_weekend'=>1,'floor'=>1,'ammount'=>5500.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>41,'is_weekend'=>1,'floor'=>1,'ammount'=>400.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>41,'is_weekend'=>1,'floor'=>1,'ammount'=>4000.0],
            ['sub_type_description'=>'For watching sports games','parent_id'=>42,'is_weekend'=>1,'floor'=>1,'ammount'=>5000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>42,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>42,'is_weekend'=>1,'floor'=>1,'ammount'=>5000.0],
            ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>43,'is_weekend'=>1,'floor'=>1,'ammount'=>6000.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>43,'is_weekend'=>1,'floor'=>1,'ammount'=>500.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>43,'is_weekend'=>1,'floor'=>1,'ammount'=>5000.0],
            ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>44,'is_weekend'=>1,'floor'=>1,'ammount'=>0.0],
            ['sub_type_description'=>'For Additional one hour','parent_id'=>44,'is_weekend'=>1,'floor'=>1,'ammount'=>0.0],
            ['sub_type_description'=>'Security Deposit','parent_id'=>44,'is_weekend'=>1,'floor'=>1,'ammount'=>0.0],            

            
            
        ]);
      
       
    }
}
