<?php

use Illuminate\Database\Seeder;

class BookingSubTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    
        DB::table('booking_tax_sub_type')->insert([

             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>1],
             ['sub_type_description'=>'for an Additional one hour','parent_id'=>1],
             ['sub_type_description'=>'Security Deposits','parent_id'=>1],
             ['sub_type_description'=>'For Water','parent_id'=>1],
             ['sub_type_description'=>'for a single show not exceeding 03 hours','parent_id'=>2],
             ['sub_type_description'=>'for 02  shows not exceeding 03 hours','parent_id'=>2],
             ['sub_type_description'=>'for 03   shows  not exceeding 03 hours','parent_id'=>2],
             ['sub_type_description'=>'for supply of water','parent_id'=>2],
             ['sub_type_description'=>'For a single show not exceeding 03 hours','parent_id'=>3],
             ['sub_type_description'=>'For 02 shows not exceeding 03 hours','parent_id'=>3],
             ['sub_type_description'=>'For 03 shows not exceeding 03 hours','parent_id'=>3],
             ['sub_type_description'=>'For every one hour exceeding','parent_id'=>3],
             ['sub_type_description'=>'Security Deposit','parent_id'=>3],
             ['sub_type_description'=>'For supply of water','parent_id'=>3],
             ['sub_type_description'=>'For a single day (for 06 hours)','parent_id'=>4],
             ['sub_type_description'=>'For every additional one hour','parent_id'=>4],
             ['sub_type_description'=>'Security Deposit','parent_id'=>4],
             ['sub_type_description'=>'For Water','parent_id'=>4],
             ['sub_type_description'=>'For a period  not exceeding 06 hours','parent_id'=>5],
             ['sub_type_description'=>'Additional one hour','parent_id'=>5],
             ['sub_type_description'=>'Security Deposit','parent_id'=>5],
             ['sub_type_description'=>'For water','parent_id'=>5],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>6],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>6],
             ['sub_type_description'=>'Security Deposit','parent_id'=>6],
             ['sub_type_description'=>'For water','parent_id'=>6],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>7],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>7],
             ['sub_type_description'=>'Security Deposit','parent_id'=>7],
             ['sub_type_description'=>'For water','parent_id'=>7],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>8],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>8],
             ['sub_type_description'=>'Security Deposit','parent_id'=>8],
             ['sub_type_description'=>'For water','parent_id'=>8],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>9],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>9],
             ['sub_type_description'=>'Security Deposit','parent_id'=>9],
             ['sub_type_description'=>'For water','parent_id'=>9],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>10],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>10],
             ['sub_type_description'=>'Security Deposit','parent_id'=>10],
             ['sub_type_description'=>'For water','parent_id'=>10],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>11],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>11],
             ['sub_type_description'=>'Security Deposit','parent_id'=>11],
             ['sub_type_description'=>'For water','parent_id'=>11],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>12],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>12],
             ['sub_type_description'=>'Security Deposit','parent_id'=>12],
             ['sub_type_description'=>'For water','parent_id'=>12],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>13],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>13],
             ['sub_type_description'=>'Security Deposit','parent_id'=>13],
             ['sub_type_description'=>'For water','parent_id'=>13],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>14],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>14],
             ['sub_type_description'=>'Security Deposit','parent_id'=>14],
             ['sub_type_description'=>'For water','parent_id'=>14],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>15],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>15],
             ['sub_type_description'=>'Security Deposit','parent_id'=>15],
             ['sub_type_description'=>'For water','parent_id'=>15],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>16],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>16],
             ['sub_type_description'=>'Security Deposit','parent_id'=>16],
             ['sub_type_description'=>'For water','parent_id'=>16],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>17],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>17],
             ['sub_type_description'=>'Security Deposit','parent_id'=>17],
             ['sub_type_description'=>'For water','parent_id'=>17],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>18],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>18],
             ['sub_type_description'=>'Security Deposit','parent_id'=>18],
             ['sub_type_description'=>'For water','parent_id'=>18],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>19],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>19],
             ['sub_type_description'=>'Security Deposit','parent_id'=>19],
             ['sub_type_description'=>'For water','parent_id'=>19],
           
             //town hall no 2 

             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>20],
             ['sub_type_description'=>'for an Additional one hour','parent_id'=>20],
             ['sub_type_description'=>'Security Deposits','parent_id'=>20],
             ['sub_type_description'=>'For Water','parent_id'=>20],
             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>21],
             ['sub_type_description'=>'for an Additional one hour','parent_id'=>21],
             ['sub_type_description'=>'Security Deposits','parent_id'=>21],
             ['sub_type_description'=>'For Water','parent_id'=>21],
             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>22],
             ['sub_type_description'=>'for an Additional one hour','parent_id'=>22],
             ['sub_type_description'=>'Security Deposits','parent_id'=>22],
             ['sub_type_description'=>'For Water','parent_id'=>22],
             ['sub_type_description'=>'for a period not exceeding 06 hours','parent_id'=>23],
             ['sub_type_description'=>'for an Additional one hour','parent_id'=>23],
             ['sub_type_description'=>'Security Deposits','parent_id'=>23],
             ['sub_type_description'=>'For Water','parent_id'=>23],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>24],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>24],
             ['sub_type_description'=>'Security Deposit','parent_id'=>24],
             ['sub_type_description'=>'For water','parent_id'=>24],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>25],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>25],
             ['sub_type_description'=>'Security Deposit','parent_id'=>25],
             ['sub_type_description'=>'For water','parent_id'=>25],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>25],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>25],
             ['sub_type_description'=>'Security Deposit','parent_id'=>25],
             ['sub_type_description'=>'For water','parent_id'=>25],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>26],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>26],
             ['sub_type_description'=>'Security Deposit','parent_id'=>26],
             ['sub_type_description'=>'For water','parent_id'=>26],
             ['sub_type_description'=>'for a single day (for 06 hours)','parent_id'=>27],
             ['sub_type_description'=>'for every Additional one hour','parent_id'=>27],
             ['sub_type_description'=>'Security Deposit','parent_id'=>27],
             ['sub_type_description'=>'For water','parent_id'=>27],

            //stadium
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>28],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>28],
             ['sub_type_description'=>'Security Deposit','parent_id'=>28],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>29],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>29],
             ['sub_type_description'=>'Security Deposit','parent_id'=>29],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>30],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>30],
             ['sub_type_description'=>'Security Deposit','parent_id'=>30],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>31],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>31],
             ['sub_type_description'=>'Security Deposit','parent_id'=>31],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>32],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>32],
             ['sub_type_description'=>'Security Deposit','parent_id'=>32],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>33],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>33],
             ['sub_type_description'=>'Security Deposit','parent_id'=>33],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>34],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>34],
             ['sub_type_description'=>'Security Deposit','parent_id'=>34],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>35],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>35],
             ['sub_type_description'=>'Security Deposit','parent_id'=>35],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>36],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>36],
             ['sub_type_description'=>'Security Deposit','parent_id'=>36],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>37],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>37],
             ['sub_type_description'=>'Security Deposit','parent_id'=>37],
             ['sub_type_description'=>'for a period not exceeding 06hrs','parent_id'=>38],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>38],
             ['sub_type_description'=>'Security Deposit','parent_id'=>38],
             ['sub_type_description'=>'From 6.00pm to 6.00am ','parent_id'=>39],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>39],
             ['sub_type_description'=>'Security Deposit','parent_id'=>39],
             ['sub_type_description'=>'For a day (06hrs)','parent_id'=>40],
             ['sub_type_description'=>'Security Deposit','parent_id'=>40],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>41],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>41],
             ['sub_type_description'=>'Security Deposit','parent_id'=>41],
             ['sub_type_description'=>'For watching sports games','parent_id'=>42],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>42],
             ['sub_type_description'=>'Security Deposit','parent_id'=>42],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>43],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>43],
             ['sub_type_description'=>'Security Deposit','parent_id'=>43],
             ['sub_type_description'=>'For a day (06hrs) ','parent_id'=>44],
             ['sub_type_description'=>'For Additional one hour','parent_id'=>44],
             ['sub_type_description'=>'Security Deposit','parent_id'=>44],

             //samanala ground
             ['sub_type_description'=>'for a single day','parent_id'=>45],
             ['sub_type_description'=>'payment of fees per day','parent_id'=>46],
             ['sub_type_description'=>'Security Deposit(Agreement has to be signed)','parent_id'=>46],
             ['sub_type_description'=>'for a per day','parent_id'=>47],
             ['sub_type_description'=>'Security Deposit','parent_id'=>47],
             ['sub_type_description'=>'for a per day','parent_id'=>48],
             ['sub_type_description'=>'for a per day','parent_id'=>49],
             ['sub_type_description'=>'for a per day','parent_id'=>50],
             ['sub_type_description'=>'for a per day','parent_id'=>51],
             ['sub_type_description'=>'for a per day','parent_id'=>52],
             ['sub_type_description'=>'Security Deposit  (Agreement has  to be signed)','parent_id'=>52],
             ['sub_type_description'=>'For rehearsal per day Rs 5000/=','parent_id'=>52],
             ['sub_type_description'=>'To clean per day','parent_id'=>52],
             ['sub_type_description'=>'payment','parent_id'=>53],
             ['sub_type_description'=>'for a per day','parent_id'=>54],
             ['sub_type_description'=>'Security  Deposit','parent_id'=>54], 
             ['sub_type_description'=>'License Fee for a day(persons who aren’t in town area)','parent_id'=>54],
             ['sub_type_description'=>'for a per day','parent_id'=>55],
             ['sub_type_description'=>'Security  Deposit','parent_id'=>55],
             ['sub_type_description'=>'for a per hour','parent_id'=>56],
             ['sub_type_description'=>'For every additional hour or part of it','parent_id'=>56],
             ['sub_type_description'=>'for a per day','parent_id'=>57],             
             ['sub_type_description'=>'Security  Deposit','parent_id'=>57],
             ['sub_type_description'=>'for a per day','parent_id'=>58],
             
             
               ]);
       
    }
}
