<?php

use Illuminate\Database\Seeder;

class IndustrialTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('industrial_types')->insert([
            [ 'description' => 'Production of Ice Cream, Yoghurt or Fruit Drinks roduction of Ice Cream, Yoghurt or Fruit Drinks','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Sale of cake products or other Bakery Products ale of cake products or other Bakery Products','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for the production of Papadum aintaining a place for the production of Papadum','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Bottling and sale of drinking water ottling and sale of drinking water','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for making Cement-sand blocks aintaining a Place for making Cement-sand blocks','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Factory aintaining a Factory','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a tinkering Place aintaining a tinkering Place','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Rice mill, sugarcane Mill or oil Mill for industrial products aintaining a Rice mill, sugarcane Mill or oil Mill for industrial products','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining an Industrial Place for Soap-making aintaining an Industrial Place for Soap-making','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the making of brush- handles aintaining a Place for the making of brush- handles','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for servicing Motorcycles Three-wheelers aintaining a Place for servicing Motorcycles Three-wheelers','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for Bicycle repairs aintaining a place for Bicycle repairs','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Motor Cycle repairs          aintaining a Place for Motor Cycle repairs         ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for three wheeler repairs aintaining a Place for three wheeler repairs','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for the repair of Motor vehicles not using Oxygen powered or mechanically operated devices aintaining a place for the repair of Motor vehicles not using Oxygen powered or mechanically operated devices','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a mechanically powered Garage aintaining a mechanically powered Garage','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a compressed gas powered Garage    aintaining a compressed gas powered Garage   ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for making grill gates and iron works aintaining a place for making grill gates and iron works','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Lathe Machine   aintaining a Lathe Machine  ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Lathe Machine   Large Scale','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Lathe Machine   Small Scale','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles epair of Injector pumps of Diesel vehicles','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles Large Scale 	','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles Small Scale	','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for making Clutch-plate of vehicles aintaining a place for making Clutch-plate of vehicles','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the Air-conditioning of Vehicles aintaining a Place for the Air-conditioning of Vehicles','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the conversion of vehicle fuel system into Gas aintaining a Place for the conversion of vehicle fuel system into Gas','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the process of vehicle alignment   and inspection aintaining a Place for the process of vehicle alignment   and inspection','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for vehicular plate bending and straightening aintaining a Place for vehicular plate bending and straightening','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for bending gutters for rain waters aintaining a Place for bending gutters for rain waters','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for repair of Radiators aintaining a Place for repair of Radiators','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers epair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers Large Scale','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers Small Scale','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Production and fabrication of Nickel Copper and Aluminium Hand rails and Stair cases roduction and fabrication of Nickel Copper and Aluminium Hand rails and Stair cases','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for carving of Memorial Plaques        aintaining a Place for carving of Memorial Plaques       ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Digital printing works aintaining a Place for Digital printing works','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil aintaining a Place for the production of Mineral oil','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of Diesel','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of petrol','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of kerosene','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of Lubricants','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for mechanical Milling of paddy into rice aintaining a Place for mechanical Milling of paddy into rice','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Production and Sale of Macaroni Noodles roduction and Sale of Macaroni Noodles','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Storage of Edible salt exceeding 10 hundredweights           torage of Edible salt exceeding 10 hundredweights          ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for making Tractor or hand Tractor     aintaining a Place for making Tractor or hand Tractor    ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Production or Storage of Fire fighting Accessories roduction or Storage of Fire fighting Accessories','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the Storage of Maldives Fish aintaining a Place for the Storage of Maldives Fish','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of other commodity by using Exercise books, Drawing Books and papers aintaining a Place for the production of other commodity by using Exercise books, Drawing Books and papers','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Aluminium works aintaining a Place for Aluminium works','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Restaurant aintaining a Restaurant','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for charging Batteries of the vehicles which are battery-operated aintaining a Place for charging Batteries of the vehicles which are battery-operated','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Jeweler Craft aintaining a Place for Jeweler Craft','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Production of boxes to contain jewellery roduction of boxes to contain jewellery','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Carving of Jeweler either manually or mechanically arving of Jeweler either manually or mechanically','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Mobile Phones (hand Phones) epair of Mobile Phones (hand Phones)','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for framing Photos aintaining a place for framing Photos','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Production and sale of Glass tanks of pet fish roduction and sale of Glass tanks of pet fish','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the repair of Television sets aintaining a Place for the repair of Television sets','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for the repair of Radio sets aintaining a place for the repair of Radio sets','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for making and sale of TV Antenna   aintaining a place for making and sale of TV Antenna  ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for the repair of Duplicating machine or type writers aintaining a place for the repair of Duplicating machine or type writers','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Instant Photos aintaining a Place for Instant Photos','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place to accept orders for processing Negatives of photos aintaining a Place to accept orders for processing Negatives of photos','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for laminating and binding of Documents or Photos aintaining a place for laminating and binding of Documents or Photos','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Studio aintaining a Studio','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place to accept orders for video filming and DVD recording aintaining a place to accept orders for video filming and DVD recording','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for repair of refrigerators aintaining a Place for repair of refrigerators','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for repair of Computers aintaining a Place for repair of Computers','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for Tailoring clothes aintaining a place for Tailoring clothes','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Tailor shop using its Clothes aintaining a Tailor shop using its Clothes','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Factory or Place for Design Sewing in clothes aintaining a Factory or Place for Design Sewing in clothes','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the sale of Sewn School bags, Hand bags travelling bags aintaining a Place for the sale of Sewn School bags, Hand bags travelling bags','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Sewing Curtains of interior House decoration   or to accept orders for the same aintaining a Place for Sewing Curtains of interior House decoration   or to accept orders for the same','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place of tatting products aintaining a place of tatting products','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Handloom Textile industry aintaining a Place for Handloom Textile industry','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of apparels aintaining a Place for the production of apparels','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Socks aintaining a Place for the production of Socks','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Acceptance of orders for cake products for Functions or Maintaining a place for classes of training  for Cake making cceptance of orders for cake products for Functions or Maintaining a place for classes of training  for Cake making','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Making Artificial leather products aking Artificial leather products','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the production of Footwear soles for the Footwear  related rubber products aintaining a Place for the production of Footwear soles for the Footwear  related rubber products','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for making rubber seals or repairing   aintaining a Place for making rubber seals or repairing  ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the repair of Watches aintaining a Place for the repair of Watches','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the sale of decorated (worked out) Saries for the Wedding functions aintaining a Place for the sale of decorated (worked out) Saries for the Wedding functions','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Gas stove or Gas stove Accessories epair of Gas stove or Gas stove Accessories','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for repair or Production of helmets aintaining a Place for repair or Production of helmets','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for repair or Construction of Naval Vessels aintaining a place for repair or Construction of Naval Vessels','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the repair of Boats aintaining a Place for the repair of Boats','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a for Fiber Glass Industry   aintaining a for Fiber Glass Industry  ','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of Sewing Machines epair of Sewing Machines','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for the labeling aintaining a Place for the labeling','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for drawing notice Board, Plastic   Number Plates aintaining a Place for drawing notice Board, Plastic   Number Plates','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Carving of Statues aintaining a Place for Carving of Statues','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Production/Creation of artificial Furniture with MD boards or  other materials roduction/Creation of artificial Furniture with MD boards or  other materials','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Saw Mill aintaining a Saw Mill','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Making of pantry Cupboard aking of pantry Cupboard','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for Carving works or Carving of Elephants aintaining a Place for Carving works or Carving of Elephants','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for Cushion works aintaining a place for Cushion works','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a Place for dying of Coir fiber aintaining a Place for dying of Coir fiber','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Bottling of Thinner paints ottling of Thinner paints','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Maintaining a place for ironwork aintaining a place for ironwork','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Repair of foot wear epair of foot wear','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Tinkering & stickered vehicles inkering & stickered vehicles','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Tinkering & stickered vehicles Three wheels','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            [ 'description' => 'Tinkering & stickered vehicles other vehicle','assessment_ammount' => 2000.0,'assessment_range_id' => 7 ],
            ]);
        DB::table('industrial_types')->insert([
            [ 'description' => 'Production of Ice Cream, Yoghurt or Fruit Drinks roduction of Ice Cream, Yoghurt or Fruit Drinks','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Sale of cake products or other Bakery Products ale of cake products or other Bakery Products','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for the production of Papadum aintaining a place for the production of Papadum','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Bottling and sale of drinking water ottling and sale of drinking water','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for making Cement-sand blocks aintaining a Place for making Cement-sand blocks','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Factory aintaining a Factory','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a tinkering Place aintaining a tinkering Place','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Rice mill, sugarcane Mill or oil Mill for industrial products aintaining a Rice mill, sugarcane Mill or oil Mill for industrial products','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining an Industrial Place for Soap-making aintaining an Industrial Place for Soap-making','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the making of brush- handles aintaining a Place for the making of brush- handles','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for servicing Motorcycles Three-wheelers aintaining a Place for servicing Motorcycles Three-wheelers','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for Bicycle repairs aintaining a place for Bicycle repairs','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Motor Cycle repairs          aintaining a Place for Motor Cycle repairs         ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for three wheeler repairs aintaining a Place for three wheeler repairs','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for the repair of Motor vehicles not using Oxygen powered or mechanically operated devices aintaining a place for the repair of Motor vehicles not using Oxygen powered or mechanically operated devices','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a mechanically powered Garage aintaining a mechanically powered Garage','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a compressed gas powered Garage    aintaining a compressed gas powered Garage   ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for making grill gates and iron works aintaining a place for making grill gates and iron works','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Lathe Machine   aintaining a Lathe Machine  ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Lathe Machine   Large Scale','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Lathe Machine   Small Scale','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles epair of Injector pumps of Diesel vehicles','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles Large Scale 	','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles Small Scale	','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for making Clutch-plate of vehicles aintaining a place for making Clutch-plate of vehicles','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the Air-conditioning of Vehicles aintaining a Place for the Air-conditioning of Vehicles','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the conversion of vehicle fuel system into Gas aintaining a Place for the conversion of vehicle fuel system into Gas','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the process of vehicle alignment   and inspection aintaining a Place for the process of vehicle alignment   and inspection','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for vehicular plate bending and straightening aintaining a Place for vehicular plate bending and straightening','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for bending gutters for rain waters aintaining a Place for bending gutters for rain waters','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for repair of Radiators aintaining a Place for repair of Radiators','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers epair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers Large Scale','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers Small Scale','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Production and fabrication of Nickel Copper and Aluminium Hand rails and Stair cases roduction and fabrication of Nickel Copper and Aluminium Hand rails and Stair cases','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for carving of Memorial Plaques        aintaining a Place for carving of Memorial Plaques       ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Digital printing works aintaining a Place for Digital printing works','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil aintaining a Place for the production of Mineral oil','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of Diesel','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of petrol','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of kerosene','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of Lubricants','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for mechanical Milling of paddy into rice aintaining a Place for mechanical Milling of paddy into rice','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Production and Sale of Macaroni Noodles roduction and Sale of Macaroni Noodles','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Storage of Edible salt exceeding 10 hundredweights           torage of Edible salt exceeding 10 hundredweights          ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for making Tractor or hand Tractor     aintaining a Place for making Tractor or hand Tractor    ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Production or Storage of Fire fighting Accessories roduction or Storage of Fire fighting Accessories','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the Storage of Maldives Fish aintaining a Place for the Storage of Maldives Fish','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of other commodity by using Exercise books, Drawing Books and papers aintaining a Place for the production of other commodity by using Exercise books, Drawing Books and papers','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Aluminium works aintaining a Place for Aluminium works','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Restaurant aintaining a Restaurant','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for charging Batteries of the vehicles which are battery-operated aintaining a Place for charging Batteries of the vehicles which are battery-operated','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Jeweler Craft aintaining a Place for Jeweler Craft','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Production of boxes to contain jewellery roduction of boxes to contain jewellery','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Carving of Jeweler either manually or mechanically arving of Jeweler either manually or mechanically','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Mobile Phones (hand Phones) epair of Mobile Phones (hand Phones)','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for framing Photos aintaining a place for framing Photos','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Production and sale of Glass tanks of pet fish roduction and sale of Glass tanks of pet fish','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the repair of Television sets aintaining a Place for the repair of Television sets','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for the repair of Radio sets aintaining a place for the repair of Radio sets','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for making and sale of TV Antenna   aintaining a place for making and sale of TV Antenna  ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for the repair of Duplicating machine or type writers aintaining a place for the repair of Duplicating machine or type writers','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Instant Photos aintaining a Place for Instant Photos','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place to accept orders for processing Negatives of photos aintaining a Place to accept orders for processing Negatives of photos','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for laminating and binding of Documents or Photos aintaining a place for laminating and binding of Documents or Photos','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Studio aintaining a Studio','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place to accept orders for video filming and DVD recording aintaining a place to accept orders for video filming and DVD recording','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for repair of refrigerators aintaining a Place for repair of refrigerators','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for repair of Computers aintaining a Place for repair of Computers','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for Tailoring clothes aintaining a place for Tailoring clothes','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Tailor shop using its Clothes aintaining a Tailor shop using its Clothes','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Factory or Place for Design Sewing in clothes aintaining a Factory or Place for Design Sewing in clothes','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the sale of Sewn School bags, Hand bags travelling bags aintaining a Place for the sale of Sewn School bags, Hand bags travelling bags','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Sewing Curtains of interior House decoration   or to accept orders for the same aintaining a Place for Sewing Curtains of interior House decoration   or to accept orders for the same','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place of tatting products aintaining a place of tatting products','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Handloom Textile industry aintaining a Place for Handloom Textile industry','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of apparels aintaining a Place for the production of apparels','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Socks aintaining a Place for the production of Socks','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Acceptance of orders for cake products for Functions or Maintaining a place for classes of training  for Cake making cceptance of orders for cake products for Functions or Maintaining a place for classes of training  for Cake making','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Making Artificial leather products aking Artificial leather products','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the production of Footwear soles for the Footwear  related rubber products aintaining a Place for the production of Footwear soles for the Footwear  related rubber products','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for making rubber seals or repairing   aintaining a Place for making rubber seals or repairing  ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the repair of Watches aintaining a Place for the repair of Watches','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the sale of decorated (worked out) Saries for the Wedding functions aintaining a Place for the sale of decorated (worked out) Saries for the Wedding functions','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Gas stove or Gas stove Accessories epair of Gas stove or Gas stove Accessories','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for repair or Production of helmets aintaining a Place for repair or Production of helmets','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for repair or Construction of Naval Vessels aintaining a place for repair or Construction of Naval Vessels','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the repair of Boats aintaining a Place for the repair of Boats','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a for Fiber Glass Industry   aintaining a for Fiber Glass Industry  ','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of Sewing Machines epair of Sewing Machines','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for the labeling aintaining a Place for the labeling','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for drawing notice Board, Plastic   Number Plates aintaining a Place for drawing notice Board, Plastic   Number Plates','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Carving of Statues aintaining a Place for Carving of Statues','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Production/Creation of artificial Furniture with MD boards or  other materials roduction/Creation of artificial Furniture with MD boards or  other materials','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Saw Mill aintaining a Saw Mill','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Making of pantry Cupboard aking of pantry Cupboard','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for Carving works or Carving of Elephants aintaining a Place for Carving works or Carving of Elephants','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for Cushion works aintaining a place for Cushion works','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a Place for dying of Coir fiber aintaining a Place for dying of Coir fiber','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Bottling of Thinner paints ottling of Thinner paints','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Maintaining a place for ironwork aintaining a place for ironwork','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Repair of foot wear epair of foot wear','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Tinkering & stickered vehicles inkering & stickered vehicles','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Tinkering & stickered vehicles Three wheels','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            [ 'description' => 'Tinkering & stickered vehicles other vehicle','assessment_ammount' => 3000.0,'assessment_range_id' => 8 ],
            ]);
        DB::table('industrial_types')->insert([
            [ 'description' => 'Production of Ice Cream, Yoghurt or Fruit Drinks roduction of Ice Cream, Yoghurt or Fruit Drinks','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Sale of cake products or other Bakery Products ale of cake products or other Bakery Products','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for the production of Papadum aintaining a place for the production of Papadum','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Bottling and sale of drinking water ottling and sale of drinking water','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for making Cement-sand blocks aintaining a Place for making Cement-sand blocks','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Factory aintaining a Factory','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a tinkering Place aintaining a tinkering Place','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Rice mill, sugarcane Mill or oil Mill for industrial products aintaining a Rice mill, sugarcane Mill or oil Mill for industrial products','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining an Industrial Place for Soap-making aintaining an Industrial Place for Soap-making','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the making of brush- handles aintaining a Place for the making of brush- handles','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for servicing Motorcycles Three-wheelers aintaining a Place for servicing Motorcycles Three-wheelers','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for Bicycle repairs aintaining a place for Bicycle repairs','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Motor Cycle repairs          aintaining a Place for Motor Cycle repairs         ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for three wheeler repairs aintaining a Place for three wheeler repairs','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for the repair of Motor vehicles not using Oxygen powered or mechanically operated devices aintaining a place for the repair of Motor vehicles not using Oxygen powered or mechanically operated devices','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a mechanically powered Garage aintaining a mechanically powered Garage','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a compressed gas powered Garage    aintaining a compressed gas powered Garage   ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for making grill gates and iron works aintaining a place for making grill gates and iron works','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Lathe Machine   aintaining a Lathe Machine  ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Lathe Machine   Large Scale','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Lathe Machine   Small Scale','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles epair of Injector pumps of Diesel vehicles','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles Large Scale 	','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Injector pumps of Diesel vehicles Small Scale	','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for making Clutch-plate of vehicles aintaining a place for making Clutch-plate of vehicles','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the Air-conditioning of Vehicles aintaining a Place for the Air-conditioning of Vehicles','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the conversion of vehicle fuel system into Gas aintaining a Place for the conversion of vehicle fuel system into Gas','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the process of vehicle alignment   and inspection aintaining a Place for the process of vehicle alignment   and inspection','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for vehicular plate bending and straightening aintaining a Place for vehicular plate bending and straightening','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for bending gutters for rain waters aintaining a Place for bending gutters for rain waters','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for repair of Radiators aintaining a Place for repair of Radiators','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers epair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers Large Scale','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Electrical Accessories (including Winding of  Motors of more than 50 Horse powers Small Scale','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Production and fabrication of Nickel Copper and Aluminium Hand rails and Stair cases roduction and fabrication of Nickel Copper and Aluminium Hand rails and Stair cases','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for carving of Memorial Plaques        aintaining a Place for carving of Memorial Plaques       ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Digital printing works aintaining a Place for Digital printing works','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil aintaining a Place for the production of Mineral oil','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of Diesel','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of petrol','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of kerosene','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Mineral oil Storage of Lubricants','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for mechanical Milling of paddy into rice aintaining a Place for mechanical Milling of paddy into rice','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Production and Sale of Macaroni Noodles roduction and Sale of Macaroni Noodles','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Storage of Edible salt exceeding 10 hundredweights           torage of Edible salt exceeding 10 hundredweights          ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for making Tractor or hand Tractor     aintaining a Place for making Tractor or hand Tractor    ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Production or Storage of Fire fighting Accessories roduction or Storage of Fire fighting Accessories','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the Storage of Maldives Fish aintaining a Place for the Storage of Maldives Fish','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of other commodity by using Exercise books, Drawing Books and papers aintaining a Place for the production of other commodity by using Exercise books, Drawing Books and papers','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Aluminium works aintaining a Place for Aluminium works','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Restaurant aintaining a Restaurant','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for charging Batteries of the vehicles which are battery-operated aintaining a Place for charging Batteries of the vehicles which are battery-operated','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Jeweler Craft aintaining a Place for Jeweler Craft','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Production of boxes to contain jewellery roduction of boxes to contain jewellery','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Carving of Jeweler either manually or mechanically arving of Jeweler either manually or mechanically','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Mobile Phones (hand Phones) epair of Mobile Phones (hand Phones)','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for framing Photos aintaining a place for framing Photos','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Production and sale of Glass tanks of pet fish roduction and sale of Glass tanks of pet fish','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the repair of Television sets aintaining a Place for the repair of Television sets','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for the repair of Radio sets aintaining a place for the repair of Radio sets','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for making and sale of TV Antenna   aintaining a place for making and sale of TV Antenna  ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for the repair of Duplicating machine or type writers aintaining a place for the repair of Duplicating machine or type writers','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Instant Photos aintaining a Place for Instant Photos','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place to accept orders for processing Negatives of photos aintaining a Place to accept orders for processing Negatives of photos','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for laminating and binding of Documents or Photos aintaining a place for laminating and binding of Documents or Photos','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Studio aintaining a Studio','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place to accept orders for video filming and DVD recording aintaining a place to accept orders for video filming and DVD recording','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for repair of refrigerators aintaining a Place for repair of refrigerators','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for repair of Computers aintaining a Place for repair of Computers','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for Tailoring clothes aintaining a place for Tailoring clothes','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Tailor shop using its Clothes aintaining a Tailor shop using its Clothes','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Factory or Place for Design Sewing in clothes aintaining a Factory or Place for Design Sewing in clothes','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the sale of Sewn School bags, Hand bags travelling bags aintaining a Place for the sale of Sewn School bags, Hand bags travelling bags','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Sewing Curtains of interior House decoration   or to accept orders for the same aintaining a Place for Sewing Curtains of interior House decoration   or to accept orders for the same','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place of tatting products aintaining a place of tatting products','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Handloom Textile industry aintaining a Place for Handloom Textile industry','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of apparels aintaining a Place for the production of apparels','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Socks aintaining a Place for the production of Socks','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Acceptance of orders for cake products for Functions or Maintaining a place for classes of training  for Cake making cceptance of orders for cake products for Functions or Maintaining a place for classes of training  for Cake making','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Making Artificial leather products aking Artificial leather products','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the production of Footwear soles for the Footwear  related rubber products aintaining a Place for the production of Footwear soles for the Footwear  related rubber products','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for making rubber seals or repairing   aintaining a Place for making rubber seals or repairing  ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the repair of Watches aintaining a Place for the repair of Watches','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the sale of decorated (worked out) Saries for the Wedding functions aintaining a Place for the sale of decorated (worked out) Saries for the Wedding functions','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Gas stove or Gas stove Accessories epair of Gas stove or Gas stove Accessories','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for repair or Production of helmets aintaining a Place for repair or Production of helmets','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for repair or Construction of Naval Vessels aintaining a place for repair or Construction of Naval Vessels','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the repair of Boats aintaining a Place for the repair of Boats','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a for Fiber Glass Industry   aintaining a for Fiber Glass Industry  ','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of Sewing Machines epair of Sewing Machines','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for the labeling aintaining a Place for the labeling','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for drawing notice Board, Plastic   Number Plates aintaining a Place for drawing notice Board, Plastic   Number Plates','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Carving of Statues aintaining a Place for Carving of Statues','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Production/Creation of artificial Furniture with MD boards or  other materials roduction/Creation of artificial Furniture with MD boards or  other materials','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Saw Mill aintaining a Saw Mill','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Making of pantry Cupboard aking of pantry Cupboard','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for Carving works or Carving of Elephants aintaining a Place for Carving works or Carving of Elephants','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for Cushion works aintaining a place for Cushion works','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a Place for dying of Coir fiber aintaining a Place for dying of Coir fiber','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Bottling of Thinner paints ottling of Thinner paints','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Maintaining a place for ironwork aintaining a place for ironwork','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Repair of foot wear epair of foot wear','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Tinkering & stickered vehicles inkering & stickered vehicles','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Tinkering & stickered vehicles Three wheels','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            [ 'description' => 'Tinkering & stickered vehicles other vehicle','assessment_ammount' => 5000.0,'assessment_range_id' => 9 ],
            ]);
    }
}