<?php

use App\License_type;
use Illuminate\Database\Seeder;

class LicenseTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('license_type')->insert([
    [ 'description' => 'Pig rearing','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Sale of Fish (Storage of Fish for whole sale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Sale of Fish (Storage for export)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Sale of meat- Sale of Labelled Frozen meat','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Shops and Saloons of Hair setting and Barbers','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Laundry','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Eating houses (10 seats or less)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Eating houses (more than 10 seats)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Tea or Coffee shops(10 seats or less)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Tea or Coffee shops(more then 10 seats)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Lodging houses','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Hotels (10 seats or less)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Hotels (more than 10 seats)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Restaurant(10 seats or less)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Restaurant(more than 10 seats)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place of sales of Poultry (caged place for the purpose of sale of meat and eggs)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Place or shop for the sale of Slaughtered and processed meat like poultry etc.','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place of Ice producing Factory','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Sweet meats','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a funeral Parlour and place to service as funeral Undertakers','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Making of coffins and storage','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Manure/Fertilizer','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Manure/Fertilizer','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Sale of Explosives, Chemicals and Fertilizers ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Tiles, Concrete pipes or other concrete based Items (large Scale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Tiles, Concrete pipes or other concrete based Items (Small Scale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining an open space or a store for the stacking of Tiles exceeding 500 Tiles','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage and sale of Cement bags exceeding 25 hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of collected used metals','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Small Scale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Large Scale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Scale of Pieces)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Animal Food except poonac exceeding 20 Hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of coconut oil by mechanical process','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place for Coir products ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a place for the storage of Battery for sale','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for Tube Volcanizing','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Garage for oxygen and Welding work','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Garage for repairing vehicles','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for servicing vehicles (Small Scale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for servicing vehicles (Large Scale)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for Spray–painting works','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of cold drinks','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Sorting and processing of Plumbago','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Plumbago','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Leather','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Maldives fish exceeding 05 hundredweight','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Crushing of Granite and making Kabok','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Excavation of pebble aggregates','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Stable, Market Place, Shed or line for Horse or Cattle','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Veterinary Treating Centre','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Rubber processing Centre','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage , Cleaning , mending and dusting the gunnies which contained manure/ Fertilizer, lime or Plumbago','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Processing of Arecanut','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Processing of pure plumbago','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a shed or a barn to cage sheeps or Goats or both not exceeding 10 in numbers','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of lime','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Potatoes exceeding 05 hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of coconut charcoal exceeding 05 hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Processing of Cinnamon, Cardamom or fiber by Sulphor Smoking','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Dried Fish exceeding 05 hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Salted Fish exceeding 10 hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Inter-weaving and drying of Rubber Ottapalu Strips','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of trunk boxes','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of variety of Glue','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of antiseptics','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for restoration or retreading of Tyres','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Empty Bottles exceeding 100','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Cinnamon Peels exceeding One hundredweight  ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of cocoa exceeding 10 hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Rubber by Licensed Dealers','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage or making of rattan products','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Concrete or Clay pipes','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining factory of loom by using mechanical power','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Cereal, except for the purpose of animal Food ,exceeding  01 Ton (except Co-operatives)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Rubber  items /Goods   ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Processing and storage of shark fins','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Grinding of Borns by mechanical Device','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Poonac exceeding 01 ton','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of polythene celluloid or perpecs and Storage','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Acid exceeding 5 Gallons','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Camphor','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Boots and Foot wear','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Candles','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Sawing of Timber or Planks by means of Steam or any other Mechanical devise','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Copra kiln','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of sesame oil by Mechanical process','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Sekku or a Hand Mill for the extraction of oil','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Fiber and Storage','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Boxes of matches','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Imbul Flakes','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Coconut oil exceeding 50 Gallons','assessment_ammount' => 2000.0,'assessment_range_id' => 1 ],
    [ 'description' => 'Storage of Methielated Spirits','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Acetylene','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Yard or Store for stacking Bricks  exceeding 250 bricks','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a yard or Store for stacking of kabok blocks exceeding 250 blocks ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Cigarette','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Beedi','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Gunnies except those used for Fertilizer, Lime or Plumbago, exceeding 100','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Rubber Tyres or Tubes Exceeding 150','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of any other Charcoal than Coconut Charcoal exceeding one hundredweights','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Boat or Barge making','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Making of Wooden Box (Production of Tea Boxes)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Printing Press operated by Manual or Pedaling devise','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a yard or Store for the storage of any other Oil than Coconut oil exceeding 50 Liter','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Sulphur or Sulphur powder exceeding 50 Kilo Grams','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Paints or Varnish','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Fire arms Cartridges exceeding 100','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Coir or Cotton flake Mattresses or pillows or Cushion products  ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Brand new tyres and Tubes exceeding 150','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of used Papers exceeding 250 Kilo grams','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for Mechanical refrigeration ','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for making shirt collar or shirt sleeve cuffs','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for dry-cleaning works','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production and Storage of Coal Gas','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Carbon Dioxide','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Melting of impure metal','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of fire work products','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of firing ingredients and explosives exceeding 02 kilograms','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Storage of Gum, Glue or resin','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Production of Floor polish','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for seep of Bitumen','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for Assembly of Motor Cars','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for the Assembly of Scooter and Motor Cycles','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Crafting & polishing jems','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for Electroplating works, Chromium plating, Gold plating  silver plating  using non mechanical process','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a power operated Garment Factory','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Place for the Storage of Timber for sale','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],
    [ 'description' => 'Maintaining a Centre for crushing of metal (mechanical)','assessment_ammount' => 2000.0,'assessment_range_id' =>  1 ],

    ]);
    
    DB::table('license_type')->insert([
        [ 'description' => 'Pig rearing','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Sale of Fish (Storage of Fish for whole sale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Sale of Fish (Storage for export)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Sale of meat- Sale of Labelled Frozen meat','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Shops and Saloons of Hair setting and Barbers','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Laundry','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Eating houses (10 seats or less)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Eating houses (more than 10 seats)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Tea or Coffee shops(10 seats or less)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Tea or Coffee shops(more then 10 seats)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Lodging houses','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Hotels (10 seats or less)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Hotels (more than 10 seats)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Restaurant(10 seats or less)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Restaurant(more than 10 seats)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place of sales of Poultry (caged place for the purpose of sale of meat and eggs)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Place or shop for the sale of Slaughtered and processed meat like poultry etc.','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place of Ice producing Factory','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Sweet meats','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a funeral Parlour and place to service as funeral Undertakers','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Making of coffins and storage','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Manure/Fertilizer','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Manure/Fertilizer','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Sale of Explosives, Chemicals and Fertilizers ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Tiles, Concrete pipes or other concrete based Items (large Scale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Tiles, Concrete pipes or other concrete based Items (Small Scale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining an open space or a store for the stacking of Tiles exceeding 500 Tiles','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage and sale of Cement bags exceeding 25 hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of collected used metals','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Small Scale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Large Scale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Scale of Pieces)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Animal Food except poonac exceeding 20 Hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of coconut oil by mechanical process','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place for Coir products ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a place for the storage of Battery for sale','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for Tube Volcanizing','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Garage for oxygen and Welding work','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Garage for repairing vehicles','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for servicing vehicles (Small Scale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for servicing vehicles (Large Scale)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for Spray–painting works','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of cold drinks','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Sorting and processing of Plumbago','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Plumbago','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Leather','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Maldives fish exceeding 05 hundredweight','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Crushing of Granite and making Kabok','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Excavation of pebble aggregates','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Stable, Market Place, Shed or line for Horse or Cattle','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Veterinary Treating Centre','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Rubber processing Centre','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage , Cleaning , mending and dusting the gunnies which contained manure/ Fertilizer, lime or Plumbago','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Processing of Arecanut','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Processing of pure plumbago','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a shed or a barn to cage sheeps or Goats or both not exceeding 10 in numbers','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of lime','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Potatoes exceeding 05 hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of coconut charcoal exceeding 05 hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Processing of Cinnamon, Cardamom or fiber by Sulphor Smoking','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Dried Fish exceeding 05 hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Salted Fish exceeding 10 hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Inter-weaving and drying of Rubber Ottapalu Strips','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of trunk boxes','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of variety of Glue','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of antiseptics','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for restoration or retreading of Tyres','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Empty Bottles exceeding 100','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Cinnamon Peels exceeding One hundredweight  ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of cocoa exceeding 10 hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Rubber by Licensed Dealers','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage or making of rattan products','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Concrete or Clay pipes','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining factory of loom by using mechanical power','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Cereal, except for the purpose of animal Food ,exceeding  01 Ton (except Co-operatives)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Rubber  items /Goods   ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Processing and storage of shark fins','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Grinding of Borns by mechanical Device','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Poonac exceeding 01 ton','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of polythene celluloid or perpecs and Storage','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Acid exceeding 5 Gallons','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Camphor','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Boots and Foot wear','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Candles','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Sawing of Timber or Planks by means of Steam or any other Mechanical devise','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Copra kiln','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of sesame oil by Mechanical process','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Sekku or a Hand Mill for the extraction of oil','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Fiber and Storage','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Boxes of matches','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Imbul Flakes','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Coconut oil exceeding 50 Gallons','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Methielated Spirits','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Acetylene','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Yard or Store for stacking Bricks  exceeding 250 bricks','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a yard or Store for stacking of kabok blocks exceeding 250 blocks ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Cigarette','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Beedi','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Gunnies except those used for Fertilizer, Lime or Plumbago, exceeding 100','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Rubber Tyres or Tubes Exceeding 150','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of any other Charcoal than Coconut Charcoal exceeding one hundredweights','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Boat or Barge making','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Making of Wooden Box (Production of Tea Boxes)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Printing Press operated by Manual or Pedaling devise','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a yard or Store for the storage of any other Oil than Coconut oil exceeding 50 Liter','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Sulphur or Sulphur powder exceeding 50 Kilo Grams','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Paints or Varnish','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Fire arms Cartridges exceeding 100','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Coir or Cotton flake Mattresses or pillows or Cushion products  ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Brand new tyres and Tubes exceeding 150','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of used Papers exceeding 250 Kilo grams','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for Mechanical refrigeration ','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for making shirt collar or shirt sleeve cuffs','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for dry-cleaning works','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production and Storage of Coal Gas','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Carbon Dioxide','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Melting of impure metal','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of fire work products','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of firing ingredients and explosives exceeding 02 kilograms','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Storage of Gum, Glue or resin','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Production of Floor polish','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for seep of Bitumen','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for Assembly of Motor Cars','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for the Assembly of Scooter and Motor Cycles','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Crafting & polishing jems','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for Electroplating works, Chromium plating, Gold plating  silver plating  using non mechanical process','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a power operated Garment Factory','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Place for the Storage of Timber for sale','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
        [ 'description' => 'Maintaining a Centre for crushing of metal (mechanical)','assessment_ammount' =>  3000.0,'assessment_range_id' =>  2 ],
    
        ]);

        DB::table('license_type')->insert([
            [ 'description' => 'Pig rearing','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Sale of Fish (Storage of Fish for whole sale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Sale of Fish (Storage for export)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Sale of meat- Sale of Labelled Frozen meat','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Shops and Saloons of Hair setting and Barbers','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Laundry','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Eating houses (10 seats or less)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Eating houses (more than 10 seats)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Tea or Coffee shops(10 seats or less)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Tea or Coffee shops(more then 10 seats)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Lodging houses','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Hotels (10 seats or less)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Hotels (more than 10 seats)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Restaurant(10 seats or less)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Restaurant(more than 10 seats)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place of sales of Poultry (caged place for the purpose of sale of meat and eggs)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Place or shop for the sale of Slaughtered and processed meat like poultry etc.','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place of Ice producing Factory','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Sweet meats','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a funeral Parlour and place to service as funeral Undertakers','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Making of coffins and storage','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Manure/Fertilizer','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Manure/Fertilizer','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Sale of Explosives, Chemicals and Fertilizers ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Tiles, Concrete pipes or other concrete based Items (large Scale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Tiles, Concrete pipes or other concrete based Items (Small Scale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining an open space or a store for the stacking of Tiles exceeding 500 Tiles','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage and sale of Cement bags exceeding 25 hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of collected used metals','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Small Scale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Large Scale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place for grinding and packing of spices or Flour (Scale of Pieces)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Animal Food except poonac exceeding 20 Hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of coconut oil by mechanical process','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place for Coir products ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a place for the storage of Battery for sale','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for Tube Volcanizing','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Garage for oxygen and Welding work','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Garage for repairing vehicles','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for servicing vehicles (Small Scale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for servicing vehicles (Large Scale)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for Spray–painting works','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of cold drinks','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Sorting and processing of Plumbago','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Plumbago','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Leather','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Maldives fish exceeding 05 hundredweight','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Crushing of Granite and making Kabok','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Excavation of pebble aggregates','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Stable, Market Place, Shed or line for Horse or Cattle','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Veterinary Treating Centre','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Rubber processing Centre','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage , Cleaning , mending and dusting the gunnies which contained manure/ Fertilizer, lime or Plumbago','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Processing of Arecanut','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Processing of pure plumbago','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a shed or a barn to cage sheeps or Goats or both not exceeding 10 in numbers','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of lime','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Potatoes exceeding 05 hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of coconut charcoal exceeding 05 hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Processing of Cinnamon, Cardamom or fiber by Sulphor Smoking','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Dried Fish exceeding 05 hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Salted Fish exceeding 10 hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Inter-weaving and drying of Rubber Ottapalu Strips','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of trunk boxes','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of variety of Glue','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of antiseptics','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for restoration or retreading of Tyres','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Empty Bottles exceeding 100','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Cinnamon Peels exceeding One hundredweight  ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of cocoa exceeding 10 hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Rubber by Licensed Dealers','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage or making of rattan products','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Concrete or Clay pipes','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining factory of loom by using mechanical power','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Cereal, except for the purpose of animal Food ,exceeding  01 Ton (except Co-operatives)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Rubber  items /Goods   ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Processing and storage of shark fins','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Grinding of Borns by mechanical Device','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Poonac exceeding 01 ton','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of polythene celluloid or perpecs and Storage','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Acid exceeding 5 Gallons','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Camphor','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Boots and Foot wear','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Candles','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Sawing of Timber or Planks by means of Steam or any other Mechanical devise','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Copra kiln','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of sesame oil by Mechanical process','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Sekku or a Hand Mill for the extraction of oil','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Fiber and Storage','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Boxes of matches','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Imbul Flakes','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Coconut oil exceeding 50 Gallons','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Methielated Spirits','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Acetylene','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Yard or Store for stacking Bricks  exceeding 250 bricks','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a yard or Store for stacking of kabok blocks exceeding 250 blocks ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Cigarette','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Beedi','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Gunnies except those used for Fertilizer, Lime or Plumbago, exceeding 100','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Rubber Tyres or Tubes Exceeding 150','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of any other Charcoal than Coconut Charcoal exceeding one hundredweights','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Boat or Barge making','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Making of Wooden Box (Production of Tea Boxes)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Printing Press operated by Manual or Pedaling devise','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a yard or Store for the storage of any other Oil than Coconut oil exceeding 50 Liter','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Sulphur or Sulphur powder exceeding 50 Kilo Grams','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Paints or Varnish','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Fire arms Cartridges exceeding 100','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Coir or Cotton flake Mattresses or pillows or Cushion products  ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Brand new tyres and Tubes exceeding 150','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of used Papers exceeding 250 Kilo grams','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for Mechanical refrigeration ','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for making shirt collar or shirt sleeve cuffs','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for dry-cleaning works','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production and Storage of Coal Gas','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Carbon Dioxide','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Melting of impure metal','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of fire work products','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of firing ingredients and explosives exceeding 02 kilograms','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Storage of Gum, Glue or resin','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Production of Floor polish','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for seep of Bitumen','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for Assembly of Motor Cars','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for the Assembly of Scooter and Motor Cycles','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Crafting & polishing jems','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for Electroplating works, Chromium plating, Gold plating  silver plating  using non mechanical process','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a power operated Garment Factory','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Place for the Storage of Timber for sale','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
            [ 'description' => 'Maintaining a Centre for crushing of metal (mechanical)','assessment_ammount' =>  5000.0,'assessment_range_id' =>  3 ],
        
            ]);
    }
}
